name: mesh-recon
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.9.79
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - expat=2.7.1
  - filelock=3.17.0
  - freeglut=3.4.0
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.22
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.4.2
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pillow=11.1.0
  - pip=25.1
  - pysocks=1.7.1
  - python=3.10.18
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.3
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tzdata=2025b
  - urllib3=2.3.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - av==14.4.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bidict==0.23.1
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==6.0.0
      - cffi==1.17.1
      - click==8.2.1
      - colorama==0.4.6
      - colorlog==6.9.0
      - comet-ml==3.49.11
      - comm==0.2.2
      - configargparse==1.7.1
      - configobj==5.0.9
      - contourpy==1.3.2
      - cryptography==45.0.4
      - cycler==0.12.1
      - dash==3.0.4
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - dill==0.4.0
      - docstring-parser==0.16
      - dulwich==0.22.8
      - everett==3.1.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fire==0.7.0
      - flask==3.0.3
      - fonttools==4.58.4
      - fpsample==0.3.3
      - fqdn==1.5.1
      - fsspec==2025.5.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.73.0
      - gsplat==1.4.0
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - ipykernel==6.29.5
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.3.2
      - jedi==0.19.2
      - joblib==1.5.1
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lightning-utilities==0.14.3
      - lxml==5.4.0
      - manifold3d==3.1.1
      - mapbox-earcut==1.0.3
      - markdown==3.8
      - markdown-it-py==3.0.0
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.4
      - mistune==3.1.3
      - msgpack==1.1.1
      - msgpack-numpy==0.4.8
      - msgspec==0.19.0
      - msvc-runtime==14.42.34433
      - multiprocess==0.70.18
      - narwhals==1.42.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nerfacc==0.5.2
      - nerfstudio==1.1.5
      - nest-asyncio==1.6.0
      - ninja==1.11.1.4
      - nodeenv==1.9.1
      - notebook==7.4.3
      - notebook-shim==0.2.4
      - nuscenes-devkit==1.1.9
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.10.0.84
      - overrides==7.7.0
      - packaging==25.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathos==0.3.4
      - platformdirs==4.3.8
      - plotly==6.1.2
      - plyfile==1.1.2
      - pox==0.3.6
      - ppft==1.7.7
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - protobuf==3.20.3
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pycocotools==2.0.10
      - pycollada==0.9
      - pycolmap==3.11.1
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pymeshlab==2023.12.post1
      - pyngrok==7.2.11
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - python-engineio==4.12.2
      - python-json-logger==3.3.0
      - python-socketio==5.13.0
      - pytorch-msssim==1.0.0
      - pywin32==310
      - pywinpty==2.0.15
      - pyzmq==27.0.0
      - rawpy==0.25.0
      - referencing==0.36.2
      - requests-toolbelt==1.0.0
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.25.1
      - rtree==1.4.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - shapely==2.1.1
      - shtab==1.7.2
      - simple-websocket==1.1.0
      - simplejson==3.20.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - splines==0.3.0
      - stack-data==0.6.3
      - svg-path==6.3
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorly==0.9.0
      - termcolor==3.1.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==0.6.7
      - tinycss2==1.4.0
      - tomli==2.2.1
      - torch-fidelity==0.3.0
      - torchaudio==2.5.1
      - torchmetrics==1.7.3
      - torchvision==0.20.1
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trimesh==4.6.12
      - typeguard==4.4.3
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tyro==0.9.24
      - uri-template==1.3.0
      - vhacdx==0.0.8.post2
      - viser==0.2.7
      - wadler-lindig==0.1.6
      - wandb==0.20.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - wsproto==1.2.0
      - wurlitzer==3.1.1
      - xatlas==0.0.10
      - xxhash==3.5.0
      - yourdfpy==0.0.57
      - zipp==3.23.0
