dataset_name: gerrard-hall         # Change this to switch datasets
data_type: individual  # choices: individual, video, internet

# These will be resolved dynamically in main.py based on dataset_name
base_data_dir: data
base_results_dir: results

use_gpu: true
run_nerf: true

automatic_reconstructor_options:
  dense: true
  use_gpu: true
  num_threads: 4
  gpu_index: [0]

feature_extractor_options:
  SiftExtraction:
    upright: true